### ISSUE TITLE
Сompile error?

### ISSUE THREAD

**Issue by gerey73** [mynenik/kForth-64#1]
/usr/bin/g++ -o kforth64  kforth.o ForthVM.o ForthCompiler.o vm64.o vmc.o -L/usr/lib:/usr/lib32 -lreadline -lncurses -ldl -lm
/usr/bin/ld: vm64.o: relocation R_X86_64_32S against symbol `GlobalSp' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
Makefile:56: recipe for target 'kforth64' failed
make[1]: *** [kforth64] Error 1
make[1]: Leaving directory '/home/ilya/forth/kForth-64-master/src'
Makefile:51: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by iru-** [comment]
Which g++, Linux and distro versions?

**Comment by gerey73** [comment]
I tried on two different computers
```
g++ (GCC) 9.1.0
Linux Arch-book 5.1.15-arch1-1-ARCH #1 SMP PREEMPT Tue Jun 25 04:49:39 UTC 2019 x86_64 GNU/Linux
```

```
g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Linux ub-home 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by mynenik** [comment]
It looks like the linker is trying to link to the 32-bit versions of the readline and ncurses libraries. Do you have the x86_64 versions of these packages installed? On an rpm system, you can query whether these packages are installed or not using

rpm -q readline
rpm -q ncurses

There is a similar query for apt. Please check for the existence of the x86_64 packages.

**Comment by gerey73** [comment]
32 and 64 versions of these libraries are installed on both computers at once.

**Comment by mynenik** [comment]
Ok. Please try the following.

In the src/ directory, edit the Makefile to change the following two lines:
CPPFLAGS = -c -Wall
CFLAGS = -c -Wall

to

CPPFLAGS = -c -fPIC -Wall
CFLAGS = -c -fPIC -Wall

Then, do "make clean" and "make".

**Comment by gerey73** [comment]
Unfortunately again
`/usr/bin/g++ -o kforth64  kforth.o ForthVM.o ForthCompiler.o vm64.o vmc.o -L/usr/lib:/usr/lib32 -lreadline -lncurses -ldl -lm
/usr/bin/ld: vm64.o: relocation R_X86_64_32S against symbol `GlobalSp' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
Makefile:56: recipe for target 'kforth64' failed
make[1]: *** [kforth64] Error 1
make[1]: Leaving directory '/home/ilya/forth/kForth-64-master/src'
Makefile:51: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by iru-** [comment]
@gerey73 could you apply the attached patch and tell me the results?

[aspic.txt](https://github.com/mynenik/kForth-64/files/3401865/aspic.txt)

**Comment by gerey73** [comment]
Sorry, but I do not quite understand what I need to do with this?
Is this a patch?

**Comment by mynenik** [comment]
@gerey73 I believe @iru- was asking you to try applying his patch for the Makefile. It looks like a diff file to me.

Can you send me your assembled vm64.o file via email for further investigation into why the linker is having relocation issues. On my fedora 30 system (gcc (GCC) 9.1.1 20190503 (Red Hat 9.1.1-1)) and on my CentOS 7 system (gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)), the kforth64 executable builds without any linker issues.

**Comment by iru-** [comment]
@mynenik I can reproduce the problem on Ubuntu 18.04. Fedora 29 is ok.

**Comment by gerey73** [comment]
> @gerey73 I
> Can you send me your assembled vm64.o file via email for further investigation into why the linker is having relocation issues. 

I sent you a file.

**Comment by mynenik** [comment]
@gerey73 I received your file. Will look into it.

@iru- Please take a look at this link. It seems that RedHat configures the default settings on the compilers to build PIE (position independent executable) files as a security measure.

https://developers.redhat.com/blog/2018/03/21/compiler-and-linker-flags-gcc/

It may be that Ubuntu and Arch use upstream defaults.

**Comment by mynenik** [comment]
@gerey73 Please try to build the current version under Ubuntu and Arch. I would like to know if the build process completes successfully.

**Comment by iru-** [comment]
@gerey73 can you try with an update revision? commit [`9662b78619739f1766d1684005c5ebd49c3d5264`](https://github.com/mynenik/kForth-64/commit/9662b78619739f1766d1684005c5ebd49c3d5264) makes it build and work on Ubuntu 18.04.2 for me.

**Comment by gerey73** [comment]
> @gerey73 Please try to build the current version under Ubuntu and Arch. I would like to know if the build process completes successfully.

Yes! Now it turned out to compile!
